# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "playwright-1.46.0" = {
      name = "playwright";
      packageName = "playwright";
      version = "1.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright/-/playwright-1.46.0.tgz";
        sha512 = "XYJ5WvfefWONh1uPAUAi0H2xXV5S3vrtcnXe6uAOgdGi3aSpqOSXX08IAjXW34xitfuOJsvXU5anXZxPSEQiJw==";
      };
    };
    "playwright-core-1.46.0" = {
      name = "playwright-core";
      packageName = "playwright-core";
      version = "1.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright-core/-/playwright-core-1.46.0.tgz";
        sha512 = "9Y/d5UIwuJk8t3+lhmMSAJyNP1BUC/DqP3cQJDQQL/oWqAiuPTLgy7Q5dzglmTLwcBRdetzgNM/gni7ckfTr6A==";
      };
    };
  };
in
{
  "@playwright/test-1.46.0" = nodeEnv.buildNodePackage {
    name = "_at_playwright_slash_test";
    packageName = "@playwright/test";
    version = "1.46.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@playwright/test/-/test-1.46.0.tgz";
      sha512 = "/QYft5VArOrGRP5pgkrfKksqsKA6CEFyGQ/gjNe6q0y4tZ1aaPfq4gIjudr1s3D+pXyrPRdsy4opKDrjBabE5w==";
    };
    dependencies = [
      sources."playwright-1.46.0"
      sources."playwright-core-1.46.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A high-level API to automate web browsers";
      homepage = "https://playwright.dev";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
