# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "playwright-1.52.0" = {
      name = "playwright";
      packageName = "playwright";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright/-/playwright-1.52.0.tgz";
        sha512 = "JAwMNMBlxJ2oD1kce4KPtMkDeKGHQstdpFPcPH3maElAXon/QZeTvtsfXmTMRyO9TslfoYOXkSsvao2nE1ilTw==";
      };
    };
    "playwright-core-1.52.0" = {
      name = "playwright-core";
      packageName = "playwright-core";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright-core/-/playwright-core-1.52.0.tgz";
        sha512 = "l2osTgLXSMeuLZOML9qYODUQoPPnUsKsb5/P6LJ2e6uPKXUdPK5WYhN4z03G+YNbWmGDY4YENauNu4ZKczreHg==";
      };
    };
  };
in
{
  "@playwright/test-1.52.0" = nodeEnv.buildNodePackage {
    name = "_at_playwright_slash_test";
    packageName = "@playwright/test";
    version = "1.52.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@playwright/test/-/test-1.52.0.tgz";
      sha512 = "uh6W7sb55hl7D6vsAeA+V2p5JnlAqzhqFyF0VcJkKZXkgnFcVG9PziERRHQfPLfNGx1C292a4JqbWzhR8L4R1g==";
    };
    dependencies = [
      sources."playwright-1.52.0"
      sources."playwright-core-1.52.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A high-level API to automate web browsers";
      homepage = "https://playwright.dev";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
