name: "CI"
on:
  pull_request:
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build .#playwright-driver
      - run: nix flake check

  automerge:
    runs-on: ubuntu-latest
    needs: [check]
    permissions: write-all
    if: contains(github.event.pull_request.labels.*.name, 'auto-update')
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
